---
- name: SSH hardening with fail2ban and 2FA
  hosts: all # change it according to your inventory file
  become: true
  vars:
    enable_google_authenticator: true
  roles:
    - fail2ban
    - pam
    - ssh
