---
- name: Validate the effective sshd configuration
  ansible.builtin.command:
    cmd: /usr/sbin/sshd -t
  changed_when: false

- name: Reload SSH
  ansible.builtin.service:
    name: ssh
    state: reloaded
