---
- name: Harden global sshd_config options
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    validate: /usr/sbin/sshd -t -f %s
  loop:
    - { regexp: '^#?PermitRootLogin', line: 'PermitRootLogin no' }
    - { regexp: '^#?PasswordAuthentication', line: 'PasswordAuthentication no' }
    - { regexp: '^#?PubkeyAuthentication', line: 'PubkeyAuthentication yes' }
    - { regexp: '^#?MaxAuthTries', line: 'MaxAuthTries 3' }
    - { regexp: '^#?AllowTcpForwarding', line: 'AllowTcpForwarding no' }
    - { regexp: '^#?ClientAliveCountMax', line: 'ClientAliveCountMax 2' }
    - { regexp: '^#?LogLevel', line: 'LogLevel VERBOSE' }
    - { regexp: '^#?MaxSessions', line: 'MaxSessions 2' }
    - { regexp: '^#?TCPKeepAlive', line: 'TCPKeepAlive no' }
    - { regexp: '^#?PermitEmptyPasswords', line: 'PermitEmptyPasswords no' }
    - { regexp: '^#?X11Forwarding', line: 'X11Forwarding no' }
    - { regexp: '^#?AllowAgentForwarding', line: 'AllowAgentForwarding no' }
    # enforce eliptic curve algorithms for key exchange and host keys
    - { regexp: '^#?HostKeyAlgorithms', line: 'HostKeyAlgorithms ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521' }
    - { regexp: '^#?KexAlgorithms', line: 'KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org' }
  notify: Restart SSH
